name: Build and Deploy to EC2

on:
  push:
    branches: [main]

env:
  IMAGE_NAME: kelomi44/weddinglite  # This sets the variable globally

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        run: |
          echo "Building and pushing image: $IMAGE_NAME:latest"
          docker build -t $IMAGE_NAME:latest .
          docker push $IMAGE_NAME:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build-and-push
    **env:**
      **IMAGE_NAME: kelomi44/weddinglite**  # ✅ Explicitly declare here

    steps:
      - name: Deploy on EC2
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            echo "Pulling image: $IMAGE_NAME:latest"
            docker pull $IMAGE_NAME:latest
            docker stop weddinglite || true && docker rm weddinglite || true
            docker run -d --name weddinglite -p 80:80 $IMAGE_NAME:latest
