name: Build and Deploy to EC2

on:
  push:
    branches: [main]

env:
  IMAGE_NAME: kelomi44/weddinglite

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    env:
      IMAGE_NAME: kelomi44/weddinglite
    steps:
      # build & push steps here...

  deploy:
    runs-on: ubuntu-latest
    needs: build-and-push
    env:
      IMAGE_NAME: kelomi44/weddinglite   # <-- ADD THIS!
    steps:
      - name: Deploy on EC2
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            docker pull $IMAGE_NAME:latest
            docker stop static-site || true && docker rm static-site || true
            docker run -d --name static-site -p 80:80 $IMAGE_NAME:latest

